/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const StudySession = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
  'completed' : IDL.Bool,
});
export const UserSettings = IDL.Record({
  'workDuration' : IDL.Int,
  'breakDuration' : IDL.Int,
});

export const idlService = IDL.Service({
  'endSession' : IDL.Func([Time], [], []),
  'getCurrentStreak' : IDL.Func([], [IDL.Int], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'weeklyTrends' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
          'dailyStudyTime' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
          'sessionDistribution' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
        }),
      ],
      ['query'],
    ),
  'login' : IDL.Func([], [], []),
  'logout' : IDL.Func([], [], []),
  'startSession' : IDL.Func([Time], [], []),
  'updateSettings' : IDL.Func([IDL.Int, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const StudySession = IDL.Record({
    'startTime' : Time,
    'endTime' : Time,
    'completed' : IDL.Bool,
  });
  const UserSettings = IDL.Record({
    'workDuration' : IDL.Int,
    'breakDuration' : IDL.Int,
  });
  
  return IDL.Service({
    'endSession' : IDL.Func([Time], [], []),
    'getCurrentStreak' : IDL.Func([], [IDL.Int], ['query']),
    'getSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'weeklyTrends' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
            'dailyStudyTime' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
            'sessionDistribution' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Int)),
          }),
        ],
        ['query'],
      ),
    'login' : IDL.Func([], [], []),
    'logout' : IDL.Func([], [], []),
    'startSession' : IDL.Func([Time], [], []),
    'updateSettings' : IDL.Func([IDL.Int, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };